#!/bin/bash
TXT=$1
PAT=$2

TXT1="1$TXT"
TXT2="2$TXT"

./fmb $TXT $TXT1 1
./fmb $TXT $TXT2 1

/usr/bin/time --quiet -f'%S %U ' ./ipmt index -a $TXT1 1> out1 2> out2
ADD=$(cat out2)
echo "index 1: "
echo "$ADD" | ./somador

/usr/bin/time --quiet -f'%S %U ' ./ipmt index -a $TXT2 1> out1 2> out2
ADD=$(cat out2)
echo "index 2: "
echo "$ADD" | ./somador

./measure_query2 $TXT1 $TXT2 $PAT

rm out1
rm out2
