#!/bin/bash
TXT=$1
CNT=1

OUTPUT=""
while [ $CNT -gt 0 ]; do
	ADD=$(/usr/bin/time --quiet -f'%S %U ' ./ipmt index $TXT 2>&1)
	OUTPUT+="$ADD"
	
	let CNT=CNT-1
done

echo "tempo medio:"
echo "$OUTPUT" | ./somador
