#!/bin/bash
TXT=$1
INDEX=$2
PAT=$3

TXT1="1$TXT"
TXT2="2$TXT"

./fmb $TXT $TXT1 1
./fmb $TXT $TXT2 1

/usr/bin/time --quiet -f'%S %U ' ./ipmt index -a $TXT1 1> out1 2> out2
ADD=$(cat out2)
echo "index 1: "
echo "$ADD" | ./somador
stat -c%s "1$INDEX"

/usr/bin/time --quiet -f'%S %U ' ./ipmt index -t $TXT2 1> out1 2> out2
ADD=$(cat out2)
echo "index 2: "
echo "$ADD" | ./somador
stat -c%s "2$INDEX"

SZ=0

while [ $SZ -lt 12 ]; do
	./gen_filter $TXT $SZ "input"
	echo "tamanho: $SZ"
	./measure_query2 $TXT1 $TXT2 "input"
	
	let SZ=SZ+2
done



rm "input"
rm out1
rm out2
