#!/bin/bash
TXT=$1
PAT=$2
CNT=3

OUTPUT1=""
OUTPUT2=""
while [ $CNT -gt 0 ]; do
	/usr/bin/time --quiet -f'%S %U ' ./ipmt search -c -p $TXT $PAT 1> out1 2> out2
	ADD=$(cat out2)
	OUTPUT1+="$ADD"
	
	/usr/bin/time --quiet -f'%S %U ' grep -c -f $PAT $TXT 1> out1 2> out2
	ADD=$(cat out2)
	if [ "$ADD" = "" ]; then
		OUTPUT2+=" 0 "
	else
		OUTPUT2+="$ADD"
	fi
	
	let CNT=CNT-1
done

echo "ipmt: "
echo "$OUTPUT1" | ./somador
echo "grep: "
echo "$OUTPUT2" | ./somador

rm out1
rm out2
